### ISSUE TITLE
pheniqs module optimization

### ISSUE THREAD

**Issue by haibol2016** [hukai916/scATACpipe#1]
@hukai916 
In [correct_barcode_pehniqs]([https://github.com/hukai916/scATACpipe/blob/main/modules/local/correct_barcode_pheniqs.nf) ,
line 53, ```{sh}
    barcode_length=\$(awk 'FNR==1 {print length(\$(NF-1))}' valid_barcode_pool.txt)
```

can be changed to the following line for better performance

 ```{sh}
    barcode_length=\$(awk 'NR==1 {print length(\$(NF-1)); exit}' valid_barcode_pool.txt)
```

**Comment by hukai916** [comment]
Thx, updated.
