### ISSUE TITLE
labelling cell clusters from 10XGENOMICS workflow

### ISSUE THREAD

**Issue by davidlyon3** [hukai916/scATACpipe#1]
Thank you for the nice pipeline.
I am a beginning in single cell bio. but I manage to run this 10XGENOMICS workflow pipeline but realize after many hours that the pipeline does not appear to label the PBMC clusters automatically from what I can see.

Can you show me exactly (since I am a beginning you may need to spell this out) how to label the PBMC Cell Clusters.

Thank you in advance.

**Comment by hukai916** [comment]
Hi @davidlyon3, thanks for your interests. 

To customize the labelings, you may need to edit the corresponding R script that was used to create the plot. Nextflow creates a separate work directory for each task, which are saved under `work/` directory by default. And the results are soft-linked to the `results/` folder by default. You can use the `ls -la` command to show the actual working folder. For example, `ls -la results/archr_clustering/jpeg/Clusters_heatmap.jpg` will show you the full actual path to it. If you navigate to the actual work folder, you will see a `run.R` script, which was used to create the plot. You can edit that file and perform custom analysis from there.

Let me know if make any sense,

**Comment by davidlyon3** [comment]
Very useful.

Thank you very much again.
