### ISSUE TITLE
typo in get_ensembl_genome_gtf_download_links.py

### ISSUE THREAD

**Issue by haibol2016** [hukai916/scATACpipe#2]
Lin 100, in [get_ensembl_genome_gtf_download_links.py](https://github.com/hukai916/scATACpipe/blob/main/bin/get_ensembl_genome_gtf_download_links.py)
    ```f.write("// Map: ucsc name to links:\n")```

"ucsc" should be "Ensembl"

**Comment by hukai916** [comment]
Thx, updated.
